(()=>{'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const SHAPES={I:[[0,0],[1,0],[2,0],[3,0]],O:[[0,0],[1,0],[0,1],[1,1]],T:[[0,0],[1,0],[2,0],[1,1]],L:[[0,0],[0,1],[0,2],[1,2]],J:[[1,0],[1,1],[1,2],[0,2]],S:[[1,0],[2,0],[0,1],[1,1]],Z:[[0,0],[1,0],[1,1],[2,1]]};
const DEFAULT_CATS=[
{id:'marmalade',names:['Marmalade','Pumpkin','Butterscotch'],primary:'#efa057',shade:'#c96e38',accent:'#fff0d2',shapes:['I','L','J'],enabled:true},
{id:'poppy',names:['Poppy','Rosie','Peaches'],primary:'#ed84ad',shade:'#ba5e86',accent:'#ffe0ec',shapes:['I','T','S'],enabled:true},
{id:'pepper',names:['Pepper','Smokey','Shadow'],primary:'#67677d',shade:'#3d3d52',accent:'#d9d9e5',shapes:['O','T','Z'],enabled:true},
{id:'biscuit',names:['Biscuit','Waffles','Mochi'],primary:'#d8af82',shade:'#9f7653',accent:'#fff0dc',shapes:['O','L','S'],enabled:true},
{id:'pickle',names:['Pickle','Minty','Sprout'],primary:'#72c6a5',shade:'#438f72',accent:'#dcfff2',shapes:['I','J','Z'],enabled:true},
{id:'socks',names:['Socks','Boots','Tux'],primary:'#8093aa',shade:'#556a82',accent:'#e4efff',shapes:['T','L','J'],enabled:true},
{id:'mittens',names:['Mittens','Snowball','Pearl'],primary:'#f4f0e9',shade:'#a7969a',accent:'#ffffff',shapes:['O','S','Z'],enabled:true}
];
const DEFAULT_LEVELS=[
{id:'cozy',name:'Cozy Box',description:'A gentle room for learning how the cats fit.',goal:6,speed:900,shapes:['I','O','T','L','J'],starter:'none'},
{id:'yarn',name:'Yarn Basket',description:'A few starter cats make every landing matter.',goal:10,speed:720,shapes:['I','O','T','L','J','S','Z'],starter:'steps'},
{id:'cafe',name:'Cat Café',description:'Keep the tables tidy while the delivery cats speed up.',goal:14,speed:560,shapes:['I','O','T','L','J','S','Z'],starter:'cups'},
{id:'zoomies',name:'Midnight Zoomies',description:'Fast cats, awkward shapes, and very little nap time.',goal:18,speed:390,shapes:['I','O','T','L','J','S','Z'],starter:'zigzag'}
];
const BOARD_THEMES={lavender:{board:'#29243c',grid:'rgba(255,255,255,.065)'},sunset:{board:'#3d2939',grid:'rgba(255,255,255,.065)'},mint:{board:'#213b3c',grid:'rgba(255,255,255,.065)'},midnight:{board:'#17192e',grid:'rgba(160,175,255,.08)'}};
const read=(k,d)=>{try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}};
const save=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v))}catch{}};
const clone=v=>JSON.parse(JSON.stringify(v));
let cats=read('akpV2Cats',clone(DEFAULT_CATS));if(!Array.isArray(cats)||!cats.length)cats=clone(DEFAULT_CATS);
let levels=[...clone(DEFAULT_LEVELS),...read('akpV2CustomLevels',[])];
let theme=read('akpV2Theme','lavender'),muted=!!read('akpV2Muted',false),selected=0,levelIndex=0,level=levels[0];
let board=[],active=null,next=null,score=0,lines=0,streak=0,paused=false,ended=false,delivering=false,last=0,dropClock=0,runId=0,audio=null,toastTimer=null;
const COLS=10,ROWS=18,CELL=32,canvas=$('#game'),ctx=canvas.getContext('2d'),nextCanvas=$('#nextCanvas'),nctx=nextCanvas.getContext('2d');
function choice(a){return a[Math.floor(Math.random()*a.length)]}
function wait(ms){return new Promise(r=>setTimeout(r,ms))}
function toast(text){const el=$('#toast');el.textContent=text;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),1800)}
function ac(){if(!audio)audio=new(window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume();return audio}
function tone(a=400,b=300,d=.12,type='sine',vol=.03,delay=0){if(muted)return;const c=ac(),o=c.createOscillator(),g=c.createGain(),t=c.currentTime+delay;o.type=type;o.frequency.setValueAtTime(a,t);o.frequency.exponentialRampToValueAtTime(Math.max(45,b),t+d);g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(vol,t+.012);g.gain.exponentialRampToValueAtTime(.0001,t+d);o.connect(g).connect(c.destination);o.start(t);o.stop(t+d+.02)}
function sound(name){if(name==='meow'){tone(510,760,.13,'triangle',.04);tone(760,390,.21,'triangle',.035,.1)}else if(name==='drop')tone(220,80,.13,'square',.022);else if(name==='turn')tone(330,490,.07,'sine',.022);else if(name==='line')[0,.07,.14].forEach((d,i)=>tone(410+i*110,520+i*120,.15,'sine',.035,d));else if(name==='win')[440,554,659,880].forEach((f,i)=>tone(f,f*1.18,.22,'triangle',.04,i*.12))}
function soundLabels(){$('#lobbySound').textContent=muted?'🔇 Sound':'🔊 Sound';$('#soundBtn').textContent=muted?'🔇':'🔊'}
function applyTheme(value){theme=['lavender','sunset','mint','midnight'].includes(value)?value:'lavender';document.body.dataset.theme=theme;$('#themeSelect').value=theme;save('akpV2Theme',theme);draw()}
function normalize(cells){const mx=Math.min(...cells.map(c=>c[0])),my=Math.min(...cells.map(c=>c[1]));return cells.map(([x,y])=>[x-mx,y-my])}
function pieceWidth(p){return Math.max(...p.cells.map(c=>c[0]))+1}
function eligibleCats(shape){let list=cats.filter(c=>c&&c.enabled!==false&&Array.isArray(c.shapes)&&c.shapes.includes(shape)&&Array.isArray(c.names)&&c.names.length);if(!list.length)list=DEFAULT_CATS.filter(c=>c.shapes.includes(shape));return list}
function makePiece(){const shape=choice(level.shapes),profile=clone(choice(eligibleCats(shape))),name=choice(profile.names.filter(Boolean));return{shape,cells:SHAPES[shape].map(c=>[...c]),x:0,y:0,profile,name}}
function round(c,x,y,w,h,r){if(c.roundRect){c.beginPath();c.roundRect(x,y,w,h,r);return}c.beginPath();c.moveTo(x+r,y);c.arcTo(x+w,y,x+w,y+h,r);c.arcTo(x+w,y+h,x,y+h,r);c.arcTo(x,y+h,x,y,r);c.arcTo(x,y,x+w,y,r)}
function cellDraw(c,gx,gy,data,size=CELL,ghost=false,preview=false){const pad=Math.max(2,size*.07),x=gx*size+pad,y=gy*size+pad,w=size-pad*2,h=size-pad*2,p=data.profile;c.save();round(c,x,y,w,h,size*.18);if(ghost){c.fillStyle='rgba(255,255,255,.07)';c.fill();c.strokeStyle='rgba(255,255,255,.52)';c.lineWidth=Math.max(1.6,size*.065);c.stroke();c.restore();return}const gr=c.createLinearGradient(x,y,x+w,y+h);gr.addColorStop(0,p.primary);gr.addColorStop(1,p.shade);c.shadowColor=p.primary+'70';c.shadowBlur=preview?7:4;c.fillStyle=gr;c.fill();c.shadowBlur=0;c.strokeStyle='rgba(255,255,255,.3)';c.lineWidth=Math.max(1,size*.035);c.stroke();if(data.face){c.fillStyle=p.primary;c.beginPath();c.moveTo(x+w*.1,y+h*.14);c.lineTo(x+w*.24,y-h*.15);c.lineTo(x+w*.39,y+h*.16);c.moveTo(x+w*.61,y+h*.16);c.lineTo(x+w*.76,y-h*.15);c.lineTo(x+w*.9,y+h*.14);c.fill();c.fillStyle='rgba(51,36,55,.82)';c.beginPath();c.arc(x+w*.34,y+h*.43,Math.max(1.3,size*.04),0,Math.PI*2);c.arc(x+w*.66,y+h*.43,Math.max(1.3,size*.04),0,Math.PI*2);c.fill();c.strokeStyle='rgba(70,45,54,.8)';c.lineWidth=Math.max(1,size*.03);c.beginPath();c.arc(x+w*.5,y+h*.56,w*.12,0,Math.PI);c.stroke()}c.restore()}
function hit(p,dx=0,dy=0,cells=p.cells){return cells.some(([cx,cy])=>{const x=p.x+cx+dx,y=p.y+cy+dy;return x<0||x>=COLS||y>=ROWS||(y>=0&&board[y][x])})}
function draw(){if(!ctx)return;const th=BOARD_THEMES[theme]||BOARD_THEMES.lavender;ctx.fillStyle=th.board;ctx.fillRect(0,0,canvas.width,canvas.height);ctx.strokeStyle=th.grid;ctx.lineWidth=1;for(let x=0;x<=COLS;x++){ctx.beginPath();ctx.moveTo(x*CELL,0);ctx.lineTo(x*CELL,ROWS*CELL);ctx.stroke()}for(let y=0;y<=ROWS;y++){ctx.beginPath();ctx.moveTo(0,y*CELL);ctx.lineTo(COLS*CELL,y*CELL);ctx.stroke()}board.forEach((row,y)=>row.forEach((data,x)=>{if(data)cellDraw(ctx,x,y,data)}));if(active){const ghost={...active,y:active.y};while(!hit(ghost,0,1))ghost.y++;ghost.cells.forEach(([x,y],i)=>cellDraw(ctx,ghost.x+x,ghost.y+y,{profile:ghost.profile,face:i===0},CELL,true));active.cells.forEach(([x,y],i)=>{if(active.y+y>=0)cellDraw(ctx,active.x+x,active.y+y,{profile:active.profile,face:i===0})})}if(paused&&!ended){ctx.fillStyle='rgba(18,16,31,.64)';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.fillStyle='white';ctx.textAlign='center';ctx.font='900 35px system-ui';ctx.fillText('Cat nap',canvas.width/2,canvas.height/2);ctx.font='700 14px system-ui';ctx.fillText('Tap Pause to continue',canvas.width/2,canvas.height/2+29)}}
function drawNext(){nctx.clearRect(0,0,nextCanvas.width,nextCanvas.height);if(!next)return;const s=25,w=pieceWidth(next)*s,h=(Math.max(...next.cells.map(c=>c[1]))+1)*s,ox=(nextCanvas.width-w)/2/s,oy=(nextCanvas.height-h)/2/s;next.cells.forEach(([x,y],i)=>cellDraw(nctx,ox+x,oy+y,{profile:next.profile,face:i===0},s,false,true));$('#nextName').textContent=next.name;$('#nextShape').textContent=next.shape+'-shape'}
function seed(){const fill=[];if(level.starter==='steps')fill.push([17,0],[17,1],[17,8],[17,9],[16,0],[16,9]);if(level.starter==='cups')fill.push([17,0],[17,1],[17,4],[17,5],[17,8],[17,9],[16,0],[16,5],[16,9]);if(level.starter==='zigzag')fill.push([17,0],[17,1],[17,4],[17,5],[17,8],[17,9],[16,1],[16,2],[16,5],[16,6],[16,9]);const roster=cats.filter(c=>c.enabled!==false);fill.forEach(([y,x],i)=>{const profile=clone(roster[i%Math.max(1,roster.length)]||DEFAULT_CATS[i%DEFAULT_CATS.length]);board[y][x]={profile,face:i%3===0}})}
function hud(){const best=read('akpV2Best',{});$('#roomName').textContent=level.name;$('#roomProgress').textContent=`${lines} / ${level.goal} lines`;$('#goalStat').textContent=`${lines}/${level.goal}`;$('#scoreStat').textContent=score.toLocaleString();$('#bestStat').textContent=(best[level.id]||0).toLocaleString();$('#streakStat').textContent=streak;$('#goalBar').style.width=Math.min(100,lines/level.goal*100)+'%'}
async function deliver(piece,id){delivering=true;active=null;draw();const w=$('#walker'),body=$('#walkerBody');body.style.setProperty('--fur',piece.profile.primary);body.style.setProperty('--shade',piece.profile.shade);w.style.setProperty('--walk',Math.max(190,$('#runway').clientWidth-112)+'px');w.className='walker';void w.offsetWidth;w.classList.add('walk');await wait(1170);if(id!==runId)return false;w.className='walker drop';sound('meow');await wait(335);if(id!==runId)return false;w.className='walker';delivering=false;return true}
async function spawn(){const id=runId;if(ended)return;if(!next)next=makePiece();const incoming=next;next=makePiece();drawNext();if(!await deliver(incoming,id)||id!==runId||ended)return;active=incoming;active.x=Math.floor((COLS-pieceWidth(active))/2);active.y=-Math.max(...active.cells.map(c=>c[1]));dropClock=0;if(hit(active))finish(false);draw()}
function move(dx,dy){if(!active||paused||ended||delivering)return false;if(!hit(active,dx,dy)){active.x+=dx;active.y+=dy;draw();return true}if(dy>0)lock();return false}
function rotate(){if(!active||paused||ended||delivering)return;const cells=active.shape==='O'?active.cells:normalize(active.cells.map(([x,y])=>[-y,x]));for(const kick of[0,-1,1,-2,2])if(!hit(active,kick,0,cells)){active.cells=cells;active.x+=kick;sound('turn');draw();return}}
function hardDrop(){if(!active||paused||ended||delivering)return;let d=0;while(!hit(active,0,1)){active.y++;d++}score+=d*2;sound('drop');lock()}
function lock(){if(!active)return;let top=false;active.cells.forEach(([x,y],i)=>{const yy=active.y+y,xx=active.x+x;if(yy<0)top=true;else board[yy][xx]={profile:active.profile,face:i===0}});active=null;if(top){finish(false);return}clearLines();hud();draw();if(!ended)spawn()}
function clearLines(){const full=[];board.forEach((row,i)=>{if(row.every(Boolean))full.push(i)});if(!full.length){streak=0;return}full.sort((a,b)=>b-a).forEach(i=>{board.splice(i,1);board.unshift(Array(COLS).fill(null))});streak++;lines+=full.length;score+=[0,100,300,600,1000][full.length]*Math.max(1,streak);sound('line');if(lines>=level.goal)finish(true)}
function finish(won){ended=true;paused=false;const best=read('akpV2Best',{});best[level.id]=Math.max(best[level.id]||0,score);save('akpV2Best',best);if(won){sound('win');save('akpV2Unlocked',Math.max(read('akpV2Unlocked',1),Math.min(levels.length,levelIndex+2)));$('#overlayFace').textContent='😻';$('#overlayTitle').textContent='Purrfect!';$('#overlayText').textContent=`${level.name} is tidy. ${lines} lines and ${score.toLocaleString()} points.`;$('#overlayBtn').textContent=levelIndex<levels.length-1?'Next room':'Play again'}else{$('#overlayFace').textContent='🙀';$('#overlayTitle').textContent='Cat pile!';$('#overlayText').textContent=`The cats reached the hatch. Score: ${score.toLocaleString()}.`;$('#overlayBtn').textContent='Try again'}$('#overlay').classList.remove('hidden');hud();renderRooms()}
function start(i){runId++;levelIndex=Math.max(0,Math.min(i,levels.length-1));level=levels[levelIndex];board=Array.from({length:ROWS},()=>Array(COLS).fill(null));seed();active=null;next=makePiece();score=0;lines=0;streak=0;paused=false;ended=false;delivering=false;$('#overlay').classList.add('hidden');$('#pauseBtn').textContent='Pause';drawNext();hud();draw();spawn()}
function renderRooms(){levels=[...clone(DEFAULT_LEVELS),...read('akpV2CustomLevels',[])];selected=Math.min(selected,levels.length-1);const unlocked=read('akpV2Unlocked',1),root=$('#roomCards');root.innerHTML=levels.map((l,i)=>`<button class="room-card ${i===selected?'active':''} ${i>=unlocked?'locked':''}" data-room="${i}" ${i>=unlocked?'disabled':''}><p class="eyebrow">${i>=unlocked?'Locked':`Level ${i+1}`}</p><strong>${escapeHtml(l.name)}</strong><span>${l.goal} lines · ${speedLabel(l.speed)}</span></button>`).join('')}
function escapeHtml(v){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function speedLabel(v){return v>=850?'Gentle':v>=650?'Playful':v>=480?'Quick':'Zoomies'}
function openPlay(){level=levels[selected];document.body.dataset.screen='play';$('#lobby').classList.add('hidden');$('#playScreen').classList.remove('hidden');start(selected)}
function returnLobby(){if(!ended&&(score>0||lines>0||active||delivering)&&!confirm('Return to the Advanced menu? The current round will restart.'))return;runId++;active=null;delivering=false;$('#playScreen').classList.add('hidden');$('#lobby').classList.remove('hidden');document.body.dataset.screen='lobby';renderRooms()}
function togglePause(){if(ended||delivering)return;paused=!paused;$('#pauseBtn').textContent=paused?'Resume':'Pause';toast(paused?'Cat nap started':'Back to play');draw()}
function action(name){ac();if(name==='left')move(-1,0);if(name==='right')move(1,0);if(name==='down'){if(move(0,1))score++;hud()}if(name==='rotate')rotate();if(name==='drop')hardDrop()}
$('#themeSelect').addEventListener('change',()=>applyTheme($('#themeSelect').value));
$('#roomCards').addEventListener('click',e=>{const b=e.target.closest('[data-room]');if(!b||b.disabled)return;selected=Number(b.dataset.room);renderRooms()});
$('#startBtn').addEventListener('click',openPlay);$('#menuBtn').addEventListener('click',returnLobby);$('#pauseBtn').addEventListener('click',togglePause);
function toggleSound(){muted=!muted;save('akpV2Muted',muted);soundLabels();if(!muted)sound('meow');toast(muted?'Cat sounds muted':'Cat sounds on')}
$('#lobbySound').addEventListener('click',toggleSound);$('#soundBtn').addEventListener('click',toggleSound);
$$('[data-action]').forEach(b=>b.addEventListener('pointerdown',e=>{e.preventDefault();action(b.dataset.action)}));
$('#overlayBtn').addEventListener('click',()=>{const won=lines>=level.goal;const target=won&&levelIndex<levels.length-1?levelIndex+1:levelIndex;selected=target;start(target)});
document.addEventListener('keydown',e=>{if(document.body.dataset.screen!=='play')return;const map={ArrowLeft:'left',ArrowRight:'right',ArrowDown:'down',ArrowUp:'rotate',' ':'rotate',Enter:'drop'};if(map[e.key]){e.preventDefault();action(map[e.key])}if(e.key.toLowerCase()==='p')togglePause();if(e.key==='Escape')returnLobby()});
let touchStart=null;canvas.addEventListener('pointerdown',e=>{touchStart={x:e.clientX,y:e.clientY,t:Date.now()}});canvas.addEventListener('pointerup',e=>{if(!touchStart)return;const dx=e.clientX-touchStart.x,dy=e.clientY-touchStart.y,dt=Date.now()-touchStart.t;touchStart=null;if(Math.abs(dx)<18&&Math.abs(dy)<18&&dt<350)rotate();else if(Math.abs(dx)>Math.abs(dy))action(dx>0?'right':'left');else if(dy>60)hardDrop();else if(dy>18)action('down')});
function frame(t){const delta=Math.min(100,t-last||0);last=t;if(document.body.dataset.screen==='play'&&!paused&&!ended&&!delivering&&active){dropClock+=delta;if(dropClock>=level.speed){move(0,1);dropClock=0}}requestAnimationFrame(frame)}
const touch=('ontouchstart' in window)||navigator.maxTouchPoints>0||matchMedia('(pointer:coarse)').matches;$('#deviceNote').textContent=touch?'Touch layout detected. The runway, board, next cat and controls stay on one gameplay screen.':'Keyboard and touch controls are both available. Classic remains available from the version dashboard.';
applyTheme(theme);soundLabels();renderRooms();requestAnimationFrame(frame);
})();
