(()=>{'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const COLS=10,ROWS=18,CELL=32,GOAL=8;
const BASE_SHAPES={I:[[0,0],[1,0],[2,0],[3,0]],O:[[0,0],[1,0],[0,1],[1,1]],T:[[0,0],[1,0],[2,0],[1,1]],L:[[0,0],[0,1],[0,2],[1,2]],J:[[1,0],[1,1],[1,2],[0,2]],S:[[1,0],[2,0],[0,1],[1,1]],Z:[[0,0],[1,0],[1,1],[2,1]]};
const CHONKY_SHAPES={P:[[0,0],[1,0],[2,0],[0,1],[1,1]],C:[[0,0],[1,0],[2,0],[3,0],[1,1]],B:[[0,0],[1,0],[0,1],[1,1],[0,2]]};
const CATS=[
{id:'marmalade',name:'Marmalade',primary:'#efa057',shade:'#c96e38'},
{id:'poppy',name:'Poppy',primary:'#ed84ad',shade:'#ba5e86'},
{id:'pepper',name:'Pepper',primary:'#747489',shade:'#424258'},
{id:'biscuit',name:'Biscuit',primary:'#d8af82',shade:'#9f7653'},
{id:'pickle',name:'Pickle',primary:'#72c6a5',shade:'#438f72'},
{id:'socks',name:'Socks',primary:'#8093aa',shade:'#556a82'}
];
const TRAITS={calm:{name:'Calm',icon:'😺',description:'Behaves normally.'},stubborn:{name:'Stubborn',icon:'🙀',description:'May refuse a rotation.'},chonky:{name:'Chonky',icon:'🐈',description:'Occupies five spaces.'}};
const FURNITURE=[[17,0],[17,9],[16,0],[16,9],[15,4],[15,5]];
const AUDIO={meows:['audio/meow-mrrp.mp3','audio/meow-soft-happy.mp3','audio/meow-cute.mp3','audio/meow-soft.mp3'],win:'audio/purr-win.mp3',gameover:'audio/retro-game-over.mp3'};
const read=(k,d)=>{try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}},save=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v))}catch{}};
const choice=a=>a[Math.floor(Math.random()*a.length)],wait=ms=>new Promise(r=>setTimeout(r,ms));
const canvas=$('#game'),ctx=canvas.getContext('2d'),nextCanvas=$('#nextCanvas'),nctx=nextCanvas.getContext('2d');
let board=[],active=null,next=null,score=0,lines=0,streak=0,paused=false,ended=false,delivering=false,locking=false,lessonOpen=false,last=0,dropClock=0,runId=0,muted=!!read('akpV3Muted',false),laserUses=2,toastTimer=null,lastMeow=-1;
let lessonsSeen=read('akpV3Lessons',{});if(!lessonsSeen||typeof lessonsSeen!=='object')lessonsSeen={};
function clone(v){return JSON.parse(JSON.stringify(v))}function pieceWidth(p){return Math.max(...p.cells.map(c=>c[0]))+1}function normalize(c){const mx=Math.min(...c.map(x=>x[0])),my=Math.min(...c.map(x=>x[1]));return c.map(([x,y])=>[x-mx,y-my])}
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>e.classList.remove('show'),1900)}
function playClip(src,vol=.75){if(muted)return;const a=new Audio(src);a.volume=vol;a.play().catch(()=>{})}
function meow(force=false){if(muted||(!force&&Math.random()>.72))return;let i=Math.floor(Math.random()*AUDIO.meows.length);if(i===lastMeow)i=(i+1)%AUDIO.meows.length;lastMeow=i;playClip(AUDIO.meows[i],.78)}
function soundLabel(){const text=muted?'🔇 Effects':'🔊 Effects';$('#lobbySound').textContent=text;$('#soundBtn').textContent=muted?'🔇':'🔊'}
function toggleSound(){muted=!muted;save('akpV3Muted',muted);soundLabel();if(!muted)meow(true);toast(muted?'Effects muted':'Effects on')}
function makePiece(){const traitRoll=Math.random();const trait=traitRoll<.25?'stubborn':traitRoll<.43?'chonky':'calm';const shapes=trait==='chonky'?CHONKY_SHAPES:BASE_SHAPES;const shape=choice(Object.keys(shapes)),profile=clone(choice(CATS));return{shape,cells:shapes[shape].map(c=>[...c]),x:0,y:0,profile,name:profile.name,trait,stubbornFailures:0}}
function round(c,x,y,w,h,r){if(c.roundRect){c.beginPath();c.roundRect(x,y,w,h,r);return}c.beginPath();c.moveTo(x+r,y);c.arcTo(x+w,y,x+w,y+h,r);c.arcTo(x+w,y+h,x,y+h,r);c.arcTo(x,y+h,x,y,r);c.arcTo(x,y,x+w,y,r)}
function drawCatCell(c,gx,gy,data,size=CELL,ghost=false,preview=false){const pad=Math.max(2,size*.07),x=gx*size+pad,y=gy*size+pad,w=size-pad*2,h=size-pad*2,p=data.profile;c.save();round(c,x,y,w,h,size*.18);if(ghost){c.fillStyle='rgba(255,255,255,.06)';c.fill();c.strokeStyle=data.trait==='chonky'?'rgba(255,205,105,.8)':'rgba(255,255,255,.52)';c.lineWidth=Math.max(1.6,size*.065);c.stroke();c.restore();return}const gr=c.createLinearGradient(x,y,x+w,y+h);gr.addColorStop(0,p.primary);gr.addColorStop(1,p.shade);c.shadowColor=p.primary+'65';c.shadowBlur=preview?7:4;c.fillStyle=gr;c.fill();c.shadowBlur=0;c.strokeStyle=data.trait==='stubborn'?'#ffd1dc':data.trait==='chonky'?'#ffe087':'rgba(255,255,255,.3)';c.lineWidth=Math.max(1,size*.045);c.stroke();if(data.face){c.fillStyle=p.primary;c.beginPath();c.moveTo(x+w*.1,y+h*.14);c.lineTo(x+w*.24,y-h*.15);c.lineTo(x+w*.39,y+h*.16);c.moveTo(x+w*.61,y+h*.16);c.lineTo(x+w*.76,y-h*.15);c.lineTo(x+w*.9,y+h*.14);c.fill();c.fillStyle='rgba(51,36,55,.82)';c.beginPath();c.arc(x+w*.34,y+h*.43,Math.max(1.3,size*.04),0,Math.PI*2);c.arc(x+w*.66,y+h*.43,Math.max(1.3,size*.04),0,Math.PI*2);c.fill()}c.restore()}
function drawFurniture(c,gx,gy,size=CELL){const x=gx*size+2,y=gy*size+2,w=size-4,h=size-4;c.save();round(c,x,y,w,h,size*.15);const gr=c.createLinearGradient(x,y,x+w,y+h);gr.addColorStop(0,'#9d7259');gr.addColorStop(1,'#654331');c.fillStyle=gr;c.fill();c.strokeStyle='#d5a785';c.lineWidth=1.5;c.stroke();c.fillStyle='rgba(255,255,255,.32)';c.fillRect(x+w*.18,y+h*.18,w*.64,Math.max(2,h*.08));c.restore()}
function hit(p,dx=0,dy=0,cells=p.cells){return cells.some(([cx,cy])=>{const x=p.x+cx+dx,y=p.y+cy+dy;return x<0||x>=COLS||y>=ROWS||(y>=0&&board[y][x])})}
function draw(){ctx.fillStyle='#2b2527';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.strokeStyle='rgba(255,255,255,.065)';for(let x=0;x<=COLS;x++){ctx.beginPath();ctx.moveTo(x*CELL,0);ctx.lineTo(x*CELL,ROWS*CELL);ctx.stroke()}for(let y=0;y<=ROWS;y++){ctx.beginPath();ctx.moveTo(0,y*CELL);ctx.lineTo(COLS*CELL,y*CELL);ctx.stroke()}board.forEach((row,y)=>row.forEach((d,x)=>{if(!d)return;if(d.furniture)drawFurniture(ctx,x,y);else drawCatCell(ctx,x,y,d)}));if(active){const g={...active,y:active.y};while(!hit(g,0,1))g.y++;g.cells.forEach(([x,y],i)=>drawCatCell(ctx,g.x+x,g.y+y,{profile:g.profile,trait:g.trait,face:i===0},CELL,true));active.cells.forEach(([x,y],i)=>active.y+y>=0&&drawCatCell(ctx,active.x+x,active.y+y,{profile:active.profile,trait:active.trait,face:i===0}))}if(paused&&!ended&&!lessonOpen){ctx.fillStyle='rgba(18,16,20,.64)';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.fillStyle='white';ctx.textAlign='center';ctx.font='900 35px system-ui';ctx.fillText('Cat nap',canvas.width/2,canvas.height/2)}}
function drawNext(){nctx.clearRect(0,0,nextCanvas.width,nextCanvas.height);if(!next)return;const s=23,w=pieceWidth(next)*s,h=(Math.max(...next.cells.map(c=>c[1]))+1)*s,ox=(nextCanvas.width-w)/2/s,oy=(nextCanvas.height-h)/2/s;next.cells.forEach(([x,y],i)=>drawCatCell(nctx,ox+x,oy+y,{profile:next.profile,trait:next.trait,face:i===0},s,false,true));$('#nextName').textContent=next.name;$('#nextShape').textContent=`${TRAITS[next.trait].name} · ${next.cells.length}-space ${next.shape}`}
function traitHud(){if(!active){$('#traitIcon').textContent='🐾';$('#traitName').textContent='Delivering';$('#traitDescription').textContent='The next cat is approaching.';$('#traitCard').dataset.trait='calm';return}const t=TRAITS[active.trait];$('#traitIcon').textContent=t.icon;$('#traitName').textContent=t.name;$('#traitDescription').textContent=t.description;$('#traitCard').dataset.trait=active.trait}
function hud(){const best=read('akpV3Best',0);$('#roomProgress').textContent=`${lines} / ${GOAL} lines`;$('#goalStat').textContent=`${lines}/${GOAL}`;$('#scoreStat').textContent=score.toLocaleString();$('#bestStat').textContent=Number(best).toLocaleString();$('#streakStat').textContent=streak;$('#goalBar').style.width=Math.min(100,lines/GOAL*100)+'%';$('#laserCount').textContent=`${laserUses} ${laserUses===1?'use':'uses'}`;$('#laserBtn').disabled=laserUses<=0||!active||ended||delivering;traitHud()}
function seedFurniture(){FURNITURE.forEach(([y,x])=>board[y][x]={furniture:true})}
async function deliver(piece,id){delivering=true;active=null;hud();draw();const w=$('#walker'),body=$('#walkerBody');body.style.setProperty('--fur',piece.profile.primary);body.style.setProperty('--shade',piece.profile.shade);w.style.setProperty('--walk',Math.max(190,$('#runway').clientWidth-112)+'px');w.className='walker';void w.offsetWidth;w.classList.add('walk');await wait(980);if(id!==runId)return false;meow(true);w.className='walker drop';await wait(310);if(id!==runId)return false;w.className='walker';delivering=false;return true}
async function spawn(){const id=runId;if(ended||locking)return;if(!next)next=makePiece();const incoming=next;next=makePiece();drawNext();if(!await deliver(incoming,id)||id!==runId||ended)return;active=incoming;active.x=Math.floor((COLS-pieceWidth(active))/2);active.y=-Math.max(...active.cells.map(c=>c[1]));dropClock=0;if(hit(active)){finish(false);return}hud();draw();if(active.trait==='chonky')showLessonOnce('chonky','🐈','Chonky cat',`${active.name} occupies five spaces instead of four. Use the landing guide before dropping.`)}
function move(dx,dy){if(!active||paused||ended||delivering||locking||lessonOpen)return false;if(!hit(active,dx,dy)){active.x+=dx;active.y+=dy;draw();return true}if(dy>0)lock();return false}
function rotate(){if(!active||paused||ended||delivering||locking||lessonOpen)return;if(active.trait==='stubborn'&&active.stubbornFailures<2&&Math.random()<.42){active.stubbornFailures++;toast(`${active.name} refused to rotate. Try again or move first.`);meow(true);showLessonOnce('stubborn','🙀','Stubborn cat',`${active.name} refused to rotate. Stubborn cats sometimes ignore a rotation command. Try again or reposition the cat.`);return}const cells=active.shape==='O'?active.cells:normalize(active.cells.map(([x,y])=>[-y,x]));for(const k of[0,-1,1,-2,2])if(!hit(active,k,0,cells)){active.cells=cells;active.x+=k;draw();return}toast('No room to rotate here.')}
function hardDrop(){if(!active||paused||ended||delivering||locking||lessonOpen)return;let d=0;while(!hit(active,0,1)){active.y++;d++}score+=d*2;lock()}
function clearLines(){let cleared=0;for(let y=ROWS-1;y>=0;y--){const row=board[y];const full=row.every(Boolean);const hasFurniture=row.some(c=>c&&c.furniture);if(full&&!hasFurniture){board.splice(y,1);board.unshift(Array(COLS).fill(null));cleared++;y++}}if(!cleared){streak=0;return 0}streak++;lines+=cleared;score+=([0,100,300,600,1000][Math.min(4,cleared)]||cleared*300)*Math.max(1,streak);return cleared}
function lock(){if(locking||!active)return;locking=true;const piece=active;active=null;let top=false;piece.cells.forEach(([x,y],i)=>{const yy=piece.y+y,xx=piece.x+x;if(yy<0)top=true;else board[yy][xx]={profile:piece.profile,trait:piece.trait,face:i===0}});if(top){locking=false;finish(false);return}clearLines();hud();draw();if(lines>=GOAL){locking=false;finish(true);return}locking=false;spawn()}
function finish(won){ended=true;paused=false;locking=false;const best=Math.max(read('akpV3Best',0),score);save('akpV3Best',best);$('#overlayFace').textContent=won?'😻':'🙀';$('#overlayTitle').textContent=won?'Room mastered!':'Cat pile!';$('#overlayText').textContent=won?`You cleared ${lines} lines and scored ${score.toLocaleString()} points in Personality Playroom.`:`The cats reached the hatch. Score: ${score.toLocaleString()}.`;$('#overlayBtn').textContent='Play again';$('#endOverlay').classList.remove('hidden');playClip(won?AUDIO.win:AUDIO.gameover,.82);hud()}
function startGame(){runId++;board=Array.from({length:ROWS},()=>Array(COLS).fill(null));seedFurniture();active=null;next=makePiece();score=0;lines=0;streak=0;paused=false;ended=false;delivering=false;locking=false;lessonOpen=false;laserUses=2;$('#endOverlay').classList.add('hidden');$('#pauseBtn').textContent='Pause';document.body.dataset.screen='play';$('#lobby').classList.add('hidden');$('#playScreen').classList.remove('hidden');drawNext();hud();draw();const taught=showLessonOnce('furniture','🛋️','Furniture blocks the room','Brown furniture spaces are permanent obstacles. They cannot be cleared, so build around them.');if(!taught)spawn()}
function returnLobby(){if(document.body.dataset.screen==='play'&&!ended&&(score>0||active||delivering)&&!confirm('Return to the Volume 3 room menu? The current round will restart.'))return;runId++;active=null;delivering=false;locking=false;lessonOpen=false;closeAllModals();$('#playScreen').classList.add('hidden');$('#lobby').classList.remove('hidden');document.body.dataset.screen='lobby'}
function togglePause(){if(ended||delivering||lessonOpen)return;paused=!paused;$('#pauseBtn').textContent=paused?'Resume':'Pause';toast(paused?'Cat nap started':'Back to play');draw()}
function action(n){if(n==='left')move(-1,0);if(n==='right')move(1,0);if(n==='down'){if(move(0,1))score++;hud()}if(n==='rotate')rotate();if(n==='drop')hardDrop()}
function openBriefing(){if(read('akpV3SkipBriefing',false)){startGame();return}$('#briefingModal').classList.remove('hidden')}
function closeAllModals(){['#briefingModal','#helpModal','#lessonModal'].forEach(id=>$(id).classList.add('hidden'))}
function showLessonOnce(key,icon,title,text){if(lessonsSeen[key])return false;lessonsSeen[key]=true;save('akpV3Lessons',lessonsSeen);lessonOpen=true;const wasPaused=paused;$('#lessonModal').dataset.wasPaused=wasPaused?'1':'0';paused=true;$('#lessonIcon').textContent=icon;$('#lessonTitle').textContent=title;$('#lessonText').textContent=text;$('#lessonModal').classList.remove('hidden');draw();return true}
function closeLesson(){lessonOpen=false;const wasPaused=$('#lessonModal').dataset.wasPaused==='1';$('#lessonModal').classList.add('hidden');paused=wasPaused;$('#pauseBtn').textContent=paused?'Resume':'Pause';draw();if(!active&&!delivering&&!ended)spawn()}
function useLaser(){if(!active||laserUses<=0||paused||ended||delivering||locking||lessonOpen)return;let bestX=active.x,bestDepth=-1,bestDistance=Infinity;for(let x=-Math.max(...active.cells.map(c=>c[0]));x<COLS;x++){const probe={...active,x};if(hit(probe,0,0))continue;let depth=0;while(!hit(probe,0,depth+1))depth++;const distance=Math.abs(x-active.x);if(depth>bestDepth||(depth===bestDepth&&distance<bestDistance)){bestDepth=depth;bestDistance=distance;bestX=x}}if(bestDepth<0){toast('The laser cannot find a safe landing.');return}active.x=bestX;laserUses--;hud();draw();toast(`Laser guided ${active.name} toward open space.`);showLessonOnce('laser','🔴','Laser pointer used','The laser moved the active cat toward the column with the deepest available landing. You have two uses per round.')}
$('#briefingBtn').addEventListener('click',openBriefing);$('#cancelBriefing').addEventListener('click',()=>$('#briefingModal').classList.add('hidden'));$('#startBtn').addEventListener('click',()=>{save('akpV3SkipBriefing',$('#skipBriefing').checked);$('#briefingModal').classList.add('hidden');startGame()});$('#menuBtn').addEventListener('click',returnLobby);$('#pauseBtn').addEventListener('click',togglePause);$('#lobbySound').addEventListener('click',toggleSound);$('#soundBtn').addEventListener('click',toggleSound);$('#helpBtn').addEventListener('click',()=>{if(ended)return;lessonOpen=true;$('#helpModal').dataset.wasPaused=paused?'1':'0';paused=true;$('#helpModal').classList.remove('hidden');draw()});$('#closeHelp').addEventListener('click',()=>{lessonOpen=false;paused=$('#helpModal').dataset.wasPaused==='1';$('#helpModal').classList.add('hidden');$('#pauseBtn').textContent=paused?'Resume':'Pause';draw()});$('#lessonBtn').addEventListener('click',closeLesson);$('#overlayBtn').addEventListener('click',startGame);$('#laserBtn').addEventListener('click',useLaser);$$('[data-action]').forEach(b=>b.addEventListener('pointerdown',e=>{e.preventDefault();action(b.dataset.action)}));
document.addEventListener('keydown',e=>{if(document.body.dataset.screen!=='play')return;const map={ArrowLeft:'left',ArrowRight:'right',ArrowDown:'down',ArrowUp:'rotate',' ':'rotate',Enter:'drop'};if(map[e.key]){e.preventDefault();action(map[e.key])}if(e.key.toLowerCase()==='l')useLaser();if(e.key.toLowerCase()==='p')togglePause();if(e.key==='Escape')returnLobby()});
let touchStart=null;canvas.addEventListener('pointerdown',e=>touchStart={x:e.clientX,y:e.clientY,t:Date.now()});canvas.addEventListener('pointerup',e=>{if(!touchStart)return;const dx=e.clientX-touchStart.x,dy=e.clientY-touchStart.y,dt=Date.now()-touchStart.t;touchStart=null;if(Math.abs(dx)<18&&Math.abs(dy)<18&&dt<350)rotate();else if(Math.abs(dx)>Math.abs(dy))action(dx>0?'right':'left');else if(dy>60)hardDrop();else if(dy>18)action('down')});
function frame(t){const delta=Math.min(100,t-last||0);last=t;if(document.body.dataset.screen==='play'&&!paused&&!ended&&!delivering&&!locking&&!lessonOpen&&active){dropClock+=delta;if(dropClock>=760){move(0,1);dropClock=0}}requestAnimationFrame(frame)}
soundLabel();draw();requestAnimationFrame(frame);
})();
